/* Distributed under the OSI-approved BSD 3-Clause License.
   See accompanying file LICENSE.rst for details.  */
/* This code was generated by llpkgc, do not edit it by hand
   See: https://gitlab.kitware.com/utils/llpkgc  */


#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifdef __SSE4_2__
 #ifdef _MSC_VER
  #include <nmmintrin.h>
 #else  /* !_MSC_VER */
  #include <x86intrin.h>
 #endif  /* _MSC_VER */
#endif  /* __SSE4_2__ */

#if defined(__ARM_NEON__) || defined(__ARM_NEON)
 #include <arm_neon.h>
#endif  /* __ARM_NEON__ */

#ifdef __wasm__
 #include <wasm_simd128.h>
#endif  /* __wasm__ */

#ifdef _MSC_VER
 #define ALIGN(n) _declspec(align(n))
 #define UNREACHABLE __assume(0)
#else  /* !_MSC_VER */
 #define ALIGN(n) __attribute__((aligned(n)))
 #define UNREACHABLE __builtin_unreachable()
#endif  /* _MSC_VER */

#include "llpkgc_frag__internal.h"

typedef int (*llpkgc_frag__internal__span_cb)(
             llpkgc_frag__internal_t*, const char*, const char*);

enum llparse_state_e {
  s_error,
  s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete,
  s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq,
  s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_sq,
  s_n_llpkgc_frag__internal__n_pkgc_frag_sq,
  s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_1,
  s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq,
  s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_escaped_char,
  s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_3,
  s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_skip_backslash,
  s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted,
  s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_2,
  s_n_llpkgc_frag__internal__n_pkgc_frag_after_quote,
  s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_dq,
  s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special_skip,
  s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_4,
  s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special,
  s_n_llpkgc_frag__internal__n_pkgc_frag_dq_keep_backslash,
  s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__lookahead_dq_backslash,
  s_n_llpkgc_frag__internal__n_pkgc_frag_dq,
  s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text,
  s_n_llpkgc_frag__internal__n_pkgc_frag_start,
};
typedef enum llparse_state_e llparse_state_t;

int llpkgc_frag__fragment_text(
    llpkgc_frag__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_frag__internal__c_update_llpkgc_frag__state(
    llpkgc_frag__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_frag__state = 2;
  return 0;
}

int llpkgc_frag__internal__c_update_llpkgc_frag__state_1(
    llpkgc_frag__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_frag__state = 1;
  return 0;
}

int llpkgc_frag__frag_complete(
    llpkgc_frag__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_frag__internal__c_update_llpkgc_frag__state_2(
    llpkgc_frag__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_frag__state = 0;
  return 0;
}

int llpkgc_frag__internal__c_update_llpkgc_frag__state_3(
    llpkgc_frag__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_frag__state = 3;
  return 0;
}

int llpkgc_frag__lookahead_dq_backslash(
    llpkgc_frag__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_frag__internal_init(llpkgc_frag__internal_t* state) {
  memset(state, 0, sizeof(*state));
  state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_start;
  return 0;
}

static llparse_state_t llpkgc_frag__internal__run(
    llpkgc_frag__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  int match;
  switch ((llparse_state_t) (intptr_t) state->_current) {
    case s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete:
    s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete: {
      switch (llpkgc_frag__frag_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_2;
        default:
          goto s_n_llpkgc_frag__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq:
    s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq;
      }
      switch (*p) {
        case '"': {
          p++;
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_1;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_sq:
    s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_sq: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_sq;
      }
      switch (*p) {
        case 39: {
          p++;
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_1;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_1;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_sq:
    s_n_llpkgc_frag__internal__n_pkgc_frag_sq: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_sq;
      }
      switch (*p) {
        case 39: {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_1;
        }
        default: {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_sq;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_1:
    s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_1: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_1;
      }
      state->_span_pos0 = (void*) p;
      goto s_n_llpkgc_frag__internal__n_pkgc_frag_sq;
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq:
    s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq;
      }
      switch (*p) {
        case 39: {
          p++;
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_3;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_1;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_escaped_char:
    s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_escaped_char: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_escaped_char;
      }
      p++;
      goto s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted;
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_3:
    s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_3: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_3;
      }
      state->_span_pos0 = (void*) p;
      goto s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_escaped_char;
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_skip_backslash:
    s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_skip_backslash: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_skip_backslash;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_3;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_2;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted:
    s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted;
      }
      switch (*p) {
        case 9: {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_2;
        }
        case ' ': {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_2;
        }
        case '"': {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_3;
        }
        case 39: {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_4;
        }
        case 92: {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_5;
        }
        default: {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_2:
    s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_2: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_2;
      }
      state->_span_pos0 = (void*) p;
      goto s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted;
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_after_quote:
    s_n_llpkgc_frag__internal__n_pkgc_frag_after_quote: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_after_quote;
      }
      switch (*p) {
        case 9: {
          goto s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete;
        }
        case ' ': {
          goto s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete;
        }
        case '"': {
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq;
        }
        case 39: {
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq;
        }
        case 92: {
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_4;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_4;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_dq:
    s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_dq: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_dq;
      }
      switch (*p) {
        case '"': {
          p++;
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_1;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_1;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special_skip:
    s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special_skip: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special_skip;
      }
      switch (*p) {
        case '"': {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
        }
        case '$': {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
        }
        case 92: {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
        }
        case '`': {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_2;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_4:
    s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_4: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_4;
      }
      state->_span_pos0 = (void*) p;
      goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special_skip;
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special:
    s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_4;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_2;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_dq_keep_backslash:
    s_n_llpkgc_frag__internal__n_pkgc_frag_dq_keep_backslash: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_dq_keep_backslash;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_error_2;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__lookahead_dq_backslash:
    s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__lookahead_dq_backslash: {
      switch (llpkgc_frag__lookahead_dq_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_6;
        case 1:
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq_keep_backslash;
        case 4:
          goto s_n_llpkgc_frag__internal__n_pause;
        default:
          goto s_n_llpkgc_frag__internal__n_error_2;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_dq:
    s_n_llpkgc_frag__internal__n_pkgc_frag_dq: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
      }
      switch (*p) {
        case '"': {
          goto s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text;
        }
        case 92: {
          goto s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__lookahead_dq_backslash;
        }
        default: {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text:
    s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text;
      }
      state->_span_pos0 = (void*) p;
      goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq;
      UNREACHABLE;
    }
    case s_n_llpkgc_frag__internal__n_pkgc_frag_start:
    s_n_llpkgc_frag__internal__n_pkgc_frag_start: {
      if (p == endp) {
        return s_n_llpkgc_frag__internal__n_pkgc_frag_start;
      }
      switch (*p) {
        case 9: {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_start;
        }
        case ' ': {
          p++;
          goto s_n_llpkgc_frag__internal__n_pkgc_frag_start;
        }
        case '"': {
          p++;
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state;
        }
        case 39: {
          p++;
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_3;
        }
        default: {
          goto s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_4;
        }
      }
      UNREACHABLE;
    }
    default:
      UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_2: {
    switch (llpkgc_frag__internal__c_update_llpkgc_frag__state_2(state, p, endp)) {
      default:
        goto s_n_llpkgc_frag__internal__n_pkgc_frag_start;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_error: {
    state->error = 0x1;
    state->reason = "Fragment complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_error_1: {
    state->error = 0x1;
    state->reason = "Fragment parse error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_1: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_sq;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_sq;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_3: {
    switch (llpkgc_frag__internal__c_update_llpkgc_frag__state_3(state, p, endp)) {
      default:
        goto s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_1;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_2: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__frag_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_3: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_pkgc_frag_consume_dq;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_4: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_pkgc_frag_consume_sq;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_error_2: {
    state->error = 0x3;
    state->reason = "Lookahead error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_5: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_skip_backslash;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_pkgc_frag_unquoted_skip_backslash;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_4: {
    switch (llpkgc_frag__internal__c_update_llpkgc_frag__state_1(state, p, endp)) {
      default:
        goto s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text_2;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state_1: {
    switch (llpkgc_frag__internal__c_update_llpkgc_frag__state_1(state, p, endp)) {
      default:
        goto s_n_llpkgc_frag__internal__n_pkgc_frag_after_quote;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_dq;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_pkgc_frag_consume_closing_dq;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_span_end_llpkgc_frag__fragment_text_6: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_frag__fragment_text(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special;
      return s_error;
    }
    goto s_n_llpkgc_frag__internal__n_pkgc_frag_dq_special;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_pause: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_frag__internal__n_invoke_llpkgc_frag__lookahead_dq_backslash;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_frag__internal__n_invoke_update_llpkgc_frag__state: {
    switch (llpkgc_frag__internal__c_update_llpkgc_frag__state(state, p, endp)) {
      default:
        goto s_n_llpkgc_frag__internal__n_span_start_llpkgc_frag__fragment_text;
    }
    UNREACHABLE;
  }
}

int llpkgc_frag__internal_execute(llpkgc_frag__internal_t* state, const char* p, const char* endp) {
  llparse_state_t next;

  /* check lingering errors */
  if (state->error != 0) {
    return state->error;
  }

  /* restart spans */
  if (state->_span_pos0 != NULL) {
    state->_span_pos0 = (void*) p;
  }

  next = llpkgc_frag__internal__run(state, (const unsigned char*) p, (const unsigned char*) endp);
  if (next == s_error) {
    return state->error;
  }
  state->_current = (void*) (intptr_t) next;

  /* execute spans */
  if (state->_span_pos0 != NULL) {
    int error;

    error = llpkgc_frag__fragment_text(state, state->_span_pos0, (const char*) endp);
    if (error != 0) {
      state->error = error;
      state->error_pos = endp;
      return error;
    }
  }

  return 0;
}
