/* Distributed under the OSI-approved BSD 3-Clause License.
   See accompanying file LICENSE.rst for details.  */
/* This code was generated by llpkgc, do not edit it by hand
   See: https://gitlab.kitware.com/utils/llpkgc  */


#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifdef __SSE4_2__
 #ifdef _MSC_VER
  #include <nmmintrin.h>
 #else  /* !_MSC_VER */
  #include <x86intrin.h>
 #endif  /* _MSC_VER */
#endif  /* __SSE4_2__ */

#if defined(__ARM_NEON__) || defined(__ARM_NEON)
 #include <arm_neon.h>
#endif  /* __ARM_NEON__ */

#ifdef __wasm__
 #include <wasm_simd128.h>
#endif  /* __wasm__ */

#ifdef _MSC_VER
 #define ALIGN(n) _declspec(align(n))
 #define UNREACHABLE __assume(0)
#else  /* !_MSC_VER */
 #define ALIGN(n) __attribute__((aligned(n)))
 #define UNREACHABLE __builtin_unreachable()
#endif  /* _MSC_VER */

#include "llpkgc_dep__internal.h"

typedef int (*llpkgc_dep__internal__span_cb)(
             llpkgc_dep__internal_t*, const char*, const char*);

enum llparse_state_e {
  s_error,
  s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete,
  s_n_llpkgc_dep__internal__n_pkgc_dep_dep_version,
  s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_version,
  s_n_llpkgc_dep__internal__n_pkgc_dep_after_op,
  s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op,
  s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_op,
  s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1,
  s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws,
  s_n_llpkgc_dep__internal__n_pkgc_dep_dep_name,
  s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name,
  s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_name,
  s_n_llpkgc_dep__internal__n_pkgc_dep_start,
};
typedef enum llparse_state_e llparse_state_t;

int llpkgc_dep__dep_name(
    llpkgc_dep__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_dep__dep_op(
    llpkgc_dep__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_dep__dep_version(
    llpkgc_dep__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_dep__internal__c_update_llpkgc_dep__state(
    llpkgc_dep__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_dep__state = 1;
  return 0;
}

int llpkgc_dep__internal__c_update_llpkgc_dep__state_1(
    llpkgc_dep__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_dep__state = 2;
  return 0;
}

int llpkgc_dep__internal__c_update_llpkgc_dep__state_2(
    llpkgc_dep__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_dep__state = 3;
  return 0;
}

int llpkgc_dep__dep_complete(
    llpkgc_dep__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_dep__internal__c_update_llpkgc_dep__state_3(
    llpkgc_dep__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_dep__state = 0;
  return 0;
}

int llpkgc_dep__internal__c_update_llpkgc_dep__state_4(
    llpkgc_dep__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_dep__state = 4;
  return 0;
}

int llpkgc_dep__internal_init(llpkgc_dep__internal_t* state) {
  memset(state, 0, sizeof(*state));
  state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_pkgc_dep_start;
  return 0;
}

static llparse_state_t llpkgc_dep__internal__run(
    llpkgc_dep__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  int match;
  switch ((llparse_state_t) (intptr_t) state->_current) {
    case s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete:
    s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete: {
      switch (llpkgc_dep__dep_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_3;
        default:
          goto s_n_llpkgc_dep__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_dep_version:
    s_n_llpkgc_dep__internal__n_pkgc_dep_dep_version: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_dep_version;
      }
      switch (*p) {
        case 9: {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_version;
        }
        case ' ': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_version;
        }
        case ',': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_version;
        }
        default: {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_version;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_version:
    s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_version: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_version;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_dep__dep_version;
      goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_version;
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_after_op:
    s_n_llpkgc_dep__internal__n_pkgc_dep_after_op: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_after_op;
      }
      switch (*p) {
        case 9: {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_after_op;
        }
        case ' ': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_after_op;
        }
        case ',': {
          goto s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
        }
        default: {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_4;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op:
    s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op;
      }
      switch (*p) {
        case '!': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op;
        }
        case '<': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op;
        }
        case '=': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op;
        }
        case '>': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op;
        }
        default: {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_2;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_op:
    s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_op: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_op;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_dep__dep_op;
      goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_op;
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1:
    s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1: {
      switch (llpkgc_dep__internal__c_update_llpkgc_dep__state_1(state, p, endp)) {
        default:
          goto s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_op;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws:
    s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
      }
      switch (*p) {
        case 9: {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
        }
        case ' ': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
        }
        case '!': {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1;
        }
        case '<': {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1;
        }
        case '=': {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1;
        }
        case '>': {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1;
        }
        default: {
          goto s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_dep_name:
    s_n_llpkgc_dep__internal__n_pkgc_dep_dep_name: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_dep_name;
      }
      switch (*p) {
        case 9: {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_2;
        }
        case ' ': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_2;
        }
        case '!': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_3;
        }
        case ',': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_4;
        }
        case '<': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_3;
        }
        case '=': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_3;
        }
        case '>': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_3;
        }
        default: {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_name;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name:
    s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name;
      }
      switch (*p) {
        case 9: {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name;
        }
        case ' ': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name;
        }
        case '!': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name;
        }
        case ',': {
          goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_1;
        }
        case '<': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name;
        }
        case '=': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name;
        }
        case '>': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name;
        }
        default: {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_5;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_name:
    s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_name: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_name;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_dep__dep_name;
      goto s_n_llpkgc_dep__internal__n_pkgc_dep_first_dep_name;
      UNREACHABLE;
    }
    case s_n_llpkgc_dep__internal__n_pkgc_dep_start:
    s_n_llpkgc_dep__internal__n_pkgc_dep_start: {
      if (p == endp) {
        return s_n_llpkgc_dep__internal__n_pkgc_dep_start;
      }
      switch (*p) {
        case 9: {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_start;
        }
        case ' ': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_start;
        }
        case ',': {
          p++;
          goto s_n_llpkgc_dep__internal__n_pkgc_dep_start;
        }
        default: {
          goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state;
        }
      }
      UNREACHABLE;
    }
    default:
      UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_3: {
    switch (llpkgc_dep__internal__c_update_llpkgc_dep__state_3(state, p, endp)) {
      default:
        goto s_n_llpkgc_dep__internal__n_pkgc_dep_start;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_error: {
    state->error = 0x1;
    state->reason = "Dep complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_version: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_version(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_4: {
    switch (llpkgc_dep__internal__c_update_llpkgc_dep__state_4(state, p, endp)) {
      default:
        goto s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_version;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_op: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_op(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_pkgc_dep_after_op;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_pkgc_dep_after_op;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_2: {
    switch (llpkgc_dep__internal__c_update_llpkgc_dep__state_2(state, p, endp)) {
      default:
        goto s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_op;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_name(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_1: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_name(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_2: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_name(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_pkgc_dep_name_ws;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_3: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_name(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_1;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_span_end_llpkgc_dep__dep_name_4: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_dep__dep_name(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
      return s_error;
    }
    goto s_n_llpkgc_dep__internal__n_invoke_llpkgc_dep__dep_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state_5: {
    switch (llpkgc_dep__internal__c_update_llpkgc_dep__state(state, p, endp)) {
      default:
        goto s_n_llpkgc_dep__internal__n_pkgc_dep_dep_name;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_dep__internal__n_invoke_update_llpkgc_dep__state: {
    switch (llpkgc_dep__internal__c_update_llpkgc_dep__state(state, p, endp)) {
      default:
        goto s_n_llpkgc_dep__internal__n_span_start_llpkgc_dep__dep_name;
    }
    UNREACHABLE;
  }
}

int llpkgc_dep__internal_execute(llpkgc_dep__internal_t* state, const char* p, const char* endp) {
  llparse_state_t next;

  /* check lingering errors */
  if (state->error != 0) {
    return state->error;
  }

  /* restart spans */
  if (state->_span_pos0 != NULL) {
    state->_span_pos0 = (void*) p;
  }

  next = llpkgc_dep__internal__run(state, (const unsigned char*) p, (const unsigned char*) endp);
  if (next == s_error) {
    return state->error;
  }
  state->_current = (void*) (intptr_t) next;

  /* execute spans */
  if (state->_span_pos0 != NULL) {
    int error;

    error = ((llpkgc_dep__internal__span_cb) state->_span_cb0)(state, state->_span_pos0, (const char*) endp);
    if (error != 0) {
      state->error = error;
      state->error_pos = endp;
      return error;
    }
  }

  return 0;
}
