/* Distributed under the OSI-approved BSD 3-Clause License.
   See accompanying file LICENSE.rst for details.  */
/* This code was generated by llpkgc, do not edit it by hand
   See: https://gitlab.kitware.com/utils/llpkgc  */


#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifdef __SSE4_2__
 #ifdef _MSC_VER
  #include <nmmintrin.h>
 #else  /* !_MSC_VER */
  #include <x86intrin.h>
 #endif  /* _MSC_VER */
#endif  /* __SSE4_2__ */

#if defined(__ARM_NEON__) || defined(__ARM_NEON)
 #include <arm_neon.h>
#endif  /* __ARM_NEON__ */

#ifdef __wasm__
 #include <wasm_simd128.h>
#endif  /* __wasm__ */

#ifdef _MSC_VER
 #define ALIGN(n) _declspec(align(n))
 #define UNREACHABLE __assume(0)
#else  /* !_MSC_VER */
 #define ALIGN(n) __attribute__((aligned(n)))
 #define UNREACHABLE __builtin_unreachable()
#endif  /* _MSC_VER */

#include "llpkgc_file__internal.h"

typedef int (*llpkgc_file__internal__span_cb)(
             llpkgc_file__internal_t*, const char*, const char*);

static const unsigned char llparse_blob0[] = {
  '\\', '\\'
};
static const unsigned char llparse_blob1[] = {
  '$', '{'
};
static const unsigned char llparse_blob2[] = {
  '\\', '\\'
};
static const unsigned char llparse_blob3[] = {
  '\\', '\\'
};

enum llparse_match_status_e {
  kMatchComplete,
  kMatchPause,
  kMatchMismatch
};
typedef enum llparse_match_status_e llparse_match_status_t;

struct llparse_match_s {
  llparse_match_status_t status;
  const unsigned char* current;
};
typedef struct llparse_match_s llparse_match_t;

static llparse_match_t llparse__match_sequence_id(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp,
    const unsigned char* seq, uint32_t seq_len) {
  uint32_t index;
  llparse_match_t res;

  index = s->_index;
  for (; p != endp; p++) {
    unsigned char current;

    current = *p;
    if (current == seq[index]) {
      if (++index == seq_len) {
        res.status = kMatchComplete;
        goto reset;
      }
    } else {
      res.status = kMatchMismatch;
      goto reset;
    }
  }
  s->_index = index;
  res.status = kMatchPause;
  res.current = p;
  return res;
reset:
  s->_index = 0;
  res.current = p;
  return res;
}

enum llparse_state_e {
  s_error,
  s_n_llpkgc_file__internal__n_pkgc_file_comment,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_literal,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_cr,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_lf,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_line_end,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_continue_line,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_2,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_escaped_comment,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_eof,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_1,
  s_n_llpkgc_file__internal__n_pkgc_file_barewords,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span,
  s_n_llpkgc_file__internal__n_pkgc_file_expect_ident_escaped_comment,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_3,
  s_n_llpkgc_file__internal__n_pkgc_file_start_barewords_backslash_eof,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_4,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete,
  s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_literal,
  s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled_literal,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_1,
  s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_2,
  s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_eof,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_2,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_2,
  s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_cr,
  s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_lf,
  s_n_llpkgc_file__internal__n_pkgc_file_line_end,
  s_n_llpkgc_file__internal__n_pkgc_file_continue_line,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_3,
  s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment,
  s_n_llpkgc_file__internal__n_pkgc_file_double_backslash,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_4,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_3,
  s_n_llpkgc_file__internal__n_pkgc_file_value_backslash_eof,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_5,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_2,
  s_n_llpkgc_file__internal__n_pkgc_file_value,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__sub_complete,
  s_n_llpkgc_file__internal__n_pkgc_file_substitution,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__sub_span,
  s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_1,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_4,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_5,
  s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_eof,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_1,
  s_n_llpkgc_file__internal__n_pkgc_file_backslash_literal,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_6,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_7,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_8,
  s_n_llpkgc_file__internal__n_pkgc_file_value_literal_backslash_eof,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_3,
  s_n_llpkgc_file__internal__n_pkgc_file_value_literal,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_6,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_7,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_8,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_4,
  s_n_llpkgc_file__internal__n_pkgc_file_expect_value,
  s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator_backslash_literal,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_6,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_7,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_5,
  s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_literal,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_cr,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_lf,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_line_end,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_continue_line,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_8,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_escaped_comment,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_double_backslash,
  s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_eof,
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_6,
  s_n_llpkgc_file__internal__n_pkgc_file_ident,
  s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5,
  s_n_llpkgc_file__internal__n_pkgc_file_expect_ident,
};
typedef enum llparse_state_e llparse_state_t;

int llpkgc_file__ident_span(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__sub_span(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__lit_span(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__lookahead_backslash(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__unfinished(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 2;
  return 0;
}

int llpkgc_file__barewords_decl_complete(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__val_complete(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__unfinished_1(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 0;
  return 0;
}

int llpkgc_file__internal__c_update_llpkgc_file__unfinished_4(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 1;
  return 0;
}

int llpkgc_file__prop_decl_complete(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__unfinished_5(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 3;
  return 0;
}

int llpkgc_file__lookahead(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 5;
  return 0;
}

int llpkgc_file__lit_complete(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__unfinished_7(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 6;
  return 0;
}

int llpkgc_file__sub_complete(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__unfinished_8(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__unfinished = 4;
  return 0;
}

int llpkgc_file__internal__c_update_llpkgc_file__value_resume(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__value_resume = 1;
  return 0;
}

int llpkgc_file__internal__c_update_llpkgc_file__line_resume(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__line_resume = 1;
  return 0;
}

int llpkgc_file__internal__c_load_llpkgc_file__line_resume(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  return state->llpkgc_file__line_resume;
}

int llpkgc_file__internal__c_load_llpkgc_file__value_resume(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  return state->llpkgc_file__value_resume;
}

int llpkgc_file__internal__c_update_llpkgc_file__text_resume(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__text_resume = 0;
  return 0;
}

int llpkgc_file__internal__c_load_llpkgc_file__text_resume(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  return state->llpkgc_file__text_resume;
}

int llpkgc_file__internal__c_update_llpkgc_file__value_resume_2(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__value_resume = 0;
  return 0;
}

int llpkgc_file__var_decl_complete(
    llpkgc_file__internal_t* s, const unsigned char* p,
    const unsigned char* endp);

int llpkgc_file__internal__c_update_llpkgc_file__line_resume_3(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  state->llpkgc_file__line_resume = 0;
  return 0;
}

int llpkgc_file__internal_init(llpkgc_file__internal_t* state) {
  memset(state, 0, sizeof(*state));
  state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
  return 0;
}

static llparse_state_t llpkgc_file__internal__run(
    llpkgc_file__internal_t* state,
    const unsigned char* p,
    const unsigned char* endp) {
  int match;
  switch ((llparse_state_t) (intptr_t) state->_current) {
    case s_n_llpkgc_file__internal__n_pkgc_file_comment:
    s_n_llpkgc_file__internal__n_pkgc_file_comment: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_comment;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        }
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        }
        default: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_comment;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete: {
      switch (llpkgc_file__barewords_decl_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        default:
          goto s_n_llpkgc_file__internal__n_error_1;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_literal;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_cr:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_cr: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_cr;
      }
      switch (*p) {
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_lf:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_lf: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_lf;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_1;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_line_end:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_line_end: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_line_end;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_cr;
        }
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_maybe_lf;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_continue_line:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_continue_line: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_continue_line;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_line_end;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_2:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_2: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_2;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_escaped_comment:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_escaped_comment: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_escaped_comment;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_2;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash: {
      llparse_match_t match_seq;

      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash;
      }
      match_seq = llparse__match_sequence_id(state, p, endp, llparse_blob0, 2);
      p = match_seq.current;
      switch (match_seq.status) {
        case kMatchComplete: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
        }
        case kMatchPause: {
          return s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash;
        }
        case kMatchMismatch: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_eof;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_1:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_1: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_literal;
        case 1:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_1;
        case 2:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_2;
        case 3:
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash;
        case 4:
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_backslash_eof;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_barewords:
    s_n_llpkgc_file__internal__n_pkgc_file_barewords: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_barewords;
      }
      switch (*p) {
        case 10: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        case 13: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        case '#': {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        case 92: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_1;
        }
        default: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_expect_ident_escaped_comment:
    s_n_llpkgc_file__internal__n_pkgc_file_expect_ident_escaped_comment: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_expect_ident_escaped_comment;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_3:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_3: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_3;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_start_barewords_backslash_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_start_barewords_backslash_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_start_barewords_backslash_eof;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_4:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_4: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_4;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_start_barewords_backslash_eof;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished;
        case 1:
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        case 2:
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident_escaped_comment;
        case 3:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_2;
        case 4:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_3;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause_1;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        default:
          goto s_n_llpkgc_file__internal__n_error_4;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_literal;
      }
      switch (*p) {
        case '$': {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled_literal;
      }
      switch (*p) {
        case '$': {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_1:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_1: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_1;
      }
      state->_span_pos1 = (void*) p;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled_literal;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled:
    s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled;
      }
      switch (*p) {
        case '$': {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_1;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_2:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_2: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        default:
          goto s_n_llpkgc_file__internal__n_error_7;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_eof;
      }
      switch (*p) {
        case '$': {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_2;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_2:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_2: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_2;
      }
      state->_span_pos1 = (void*) p;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_eof;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_2:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_2: {
      switch (llpkgc_file__lookahead(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_6;
        case 1:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution;
        case 2:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled;
        case 3:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_9;
        case 4:
          goto s_n_llpkgc_file__internal__n_pause_2;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_cr:
    s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_cr: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_cr;
      }
      switch (*p) {
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__line_resume;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__line_resume;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_lf:
    s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_lf: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_lf;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__line_resume;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__line_resume;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_line_end:
    s_n_llpkgc_file__internal__n_pkgc_file_line_end: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_line_end;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_cr;
        }
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_line_maybe_lf;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_continue_line:
    s_n_llpkgc_file__internal__n_pkgc_file_continue_line: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_continue_line;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_line_end;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_3:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_3: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_3;
      }
      state->_span_pos1 = (void*) p;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment:
    s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_10;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_double_backslash:
    s_n_llpkgc_file__internal__n_pkgc_file_double_backslash: {
      llparse_match_t match_seq;

      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_double_backslash;
      }
      match_seq = llparse__match_sequence_id(state, p, endp, llparse_blob2, 2);
      p = match_seq.current;
      switch (match_seq.status) {
        case kMatchComplete: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__text_resume;
        }
        case kMatchPause: {
          return s_n_llpkgc_file__internal__n_pkgc_file_double_backslash;
        }
        case kMatchMismatch: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_4:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_4: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_4;
      }
      state->_span_pos1 = (void*) p;
      goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_3:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_3: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        default:
          goto s_n_llpkgc_file__internal__n_error_8;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_backslash_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_value_backslash_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_backslash_eof;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_3;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_5:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_5: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_5;
      }
      state->_span_pos1 = (void*) p;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_backslash_eof;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_2:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_2: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_6;
        case 1:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__value_resume;
        case 2:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment;
        case 3:
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_4;
        case 4:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_11;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause_3;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value:
    s_n_llpkgc_file__internal__n_pkgc_file_value: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value;
      }
      switch (*p) {
        case 10: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        }
        case 13: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        }
        case '#': {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        }
        case '$': {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_2;
        }
        case 92: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_2;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_10;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__sub_complete:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__sub_complete: {
      switch (llpkgc_file__sub_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_8;
        default:
          goto s_n_llpkgc_file__internal__n_error_6;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_substitution:
    s_n_llpkgc_file__internal__n_pkgc_file_substitution: {
      static uint8_t lookup_table[] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      };
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_substitution;
      }
      switch (lookup_table[(uint8_t) *p]) {
        case 1: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_substitution;
        }
        case 2: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__sub_span;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error_9;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__sub_span:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__sub_span: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__sub_span;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__sub_span;
      goto s_n_llpkgc_file__internal__n_pkgc_file_substitution;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution:
    s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution: {
      llparse_match_t match_seq;

      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution;
      }
      match_seq = llparse__match_sequence_id(state, p, endp, llparse_blob1, 2);
      p = match_seq.current;
      switch (match_seq.status) {
        case kMatchComplete: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_7;
        }
        case kMatchPause: {
          return s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution;
        }
        case kMatchMismatch: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_1:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_1: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution;
        default:
          goto s_n_llpkgc_file__internal__n_error_5;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_4:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_4: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled;
        default:
          goto s_n_llpkgc_file__internal__n_error_10;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_5:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_5: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        default:
          goto s_n_llpkgc_file__internal__n_error_11;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_eof;
      }
      switch (*p) {
        case '$': {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_5;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_1:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_1: {
      switch (llpkgc_file__lookahead(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_literal;
        case 1:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_1;
        case 2:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_4;
        case 3:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal_dollar_eof;
        case 4:
          goto s_n_llpkgc_file__internal__n_pause_4;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_backslash_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_backslash_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_backslash_literal;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__text_resume;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_6:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_6: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__value_resume_1;
        default:
          goto s_n_llpkgc_file__internal__n_error_12;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_7:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_7: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment;
        default:
          goto s_n_llpkgc_file__internal__n_error_13;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_8:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_8: {
      switch (llpkgc_file__lit_complete(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        default:
          goto s_n_llpkgc_file__internal__n_error_14;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_literal_backslash_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_value_literal_backslash_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_literal_backslash_eof;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_8;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_3:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_3: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume_1;
        case 1:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_6;
        case 2:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_7;
        case 3:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume_2;
        case 4:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal_backslash_eof;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause_5;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_value_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_value_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
      }
      switch (*p) {
        case 10: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span;
        }
        case 13: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span;
        }
        case '#': {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span;
        }
        case '$': {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_1;
        }
        case 92: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_3;
        }
        default: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span;
      }
      state->_span_pos1 = (void*) p;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_6:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_6: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_6;
      }
      state->_span_pos1 = (void*) p;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_eof;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead: {
      switch (llpkgc_file__lookahead(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_6;
        case 1:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_substitution;
        case 2:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_dollar_doubled;
        case 3:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_12;
        case 4:
          goto s_n_llpkgc_file__internal__n_pause_6;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_7:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_7: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_7;
      }
      state->_span_pos1 = (void*) p;
      goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume_3;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_8:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_8: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_8;
      }
      state->_span_pos1 = (void*) p;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_value_backslash_eof;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_4:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_4: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_6;
        case 1:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__value_resume_2;
        case 2:
          goto s_n_llpkgc_file__internal__n_pkgc_file_value_escaped_comment;
        case 3:
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_7;
        case 4:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_13;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause_7;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_expect_value:
    s_n_llpkgc_file__internal__n_pkgc_file_expect_value: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_expect_value;
      }
      switch (*p) {
        case 10: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        }
        case 13: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        }
        case '#': {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete;
        }
        case '$': {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead;
        }
        case 92: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_4;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_10;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator_backslash_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator_backslash_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator_backslash_literal;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_6:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_6: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_6;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_double_backslash;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_7:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_7: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_7;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_start_barewords_backslash_eof;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_5:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_5: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator_backslash_literal;
        case 1:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume_3;
        case 2:
          goto s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator_backslash_literal;
        case 3:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_14;
        case 4:
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_15;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause_8;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator:
    s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator;
      }
      switch (*p) {
        case 9: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator;
        }
        case 10: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete;
        }
        case 13: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete;
        }
        case ' ': {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator;
        }
        case '#': {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete;
        }
        case ':': {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__prop_decl_complete;
        }
        case '=': {
          p++;
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__var_decl_complete;
        }
        case 92: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_5;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_literal:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_literal: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_literal;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_cr:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_cr: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_cr;
      }
      switch (*p) {
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_lf:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_lf: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_lf;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_line_end:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_line_end: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_line_end;
      }
      switch (*p) {
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_cr;
        }
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident_maybe_lf;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_continue_line:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_continue_line: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_continue_line;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident_line_end;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_8:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_8: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_8;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      p++;
      goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_escaped_comment:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_escaped_comment: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_escaped_comment;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_8;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_double_backslash:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_double_backslash: {
      llparse_match_t match_seq;

      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_double_backslash;
      }
      match_seq = llparse__match_sequence_id(state, p, endp, llparse_blob3, 2);
      p = match_seq.current;
      switch (match_seq.status) {
        case kMatchComplete: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
        }
        case kMatchPause: {
          return s_n_llpkgc_file__internal__n_pkgc_file_ident_double_backslash;
        }
        case kMatchMismatch: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_eof:
    s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_eof: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_eof;
      }
      switch (*p) {
        case 92: {
          p++;
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_error;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_6:
    s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_6: {
      switch (llpkgc_file__lookahead_backslash(state, p, endp)) {
        case 0:
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_literal;
        case 1:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_4;
        case 2:
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_5;
        case 3:
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident_double_backslash;
        case 4:
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident_backslash_eof;
        case 5:
          goto s_n_llpkgc_file__internal__n_pause_9;
        default:
          goto s_n_llpkgc_file__internal__n_error;
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_ident:
    s_n_llpkgc_file__internal__n_pkgc_file_ident: {
      static uint8_t lookup_table[] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 0, 0, 1, 0, 0,
        0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 4, 0, 0, 3,
        0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      };
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_ident;
      }
      switch (lookup_table[(uint8_t) *p]) {
        case 1: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_3;
        }
        case 2: {
          goto s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span;
        }
        case 3: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_ident;
        }
        case 4: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_6;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_pkgc_file_barewords;
        }
      }
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5:
    s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5;
      }
      state->_span_pos0 = (void*) p;
      state->_span_cb0 = llpkgc_file__ident_span;
      goto s_n_llpkgc_file__internal__n_pkgc_file_ident;
      UNREACHABLE;
    }
    case s_n_llpkgc_file__internal__n_pkgc_file_expect_ident:
    s_n_llpkgc_file__internal__n_pkgc_file_expect_ident: {
      if (p == endp) {
        return s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
      }
      switch (*p) {
        case 9: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        }
        case 10: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        }
        case 13: {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        }
        case ' ': {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
        }
        case '#': {
          p++;
          goto s_n_llpkgc_file__internal__n_pkgc_file_comment;
        }
        case 92: {
          goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash;
        }
        default: {
          goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_4;
        }
      }
      UNREACHABLE;
    }
    default:
      UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_1: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_1(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_expect_ident;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_2: {
    state->error = 0xa;
    state->reason = "Value complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__val_complete: {
    switch (llpkgc_file__val_complete(state, p, endp)) {
      case 0:
        goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_1;
      default:
        goto s_n_llpkgc_file__internal__n_error_2;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_1: {
    state->error = 0x9;
    state->reason = "Barewords complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__ident_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__barewords_decl_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error: {
    state->error = 0xe;
    state->reason = "Lookahead error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_1: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__ident_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) (p + 1);
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_pkgc_file_barewords_continue_line;
      return s_error;
    }
    p++;
    goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_continue_line;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_2: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__ident_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) (p + 1);
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_pkgc_file_barewords_escaped_comment;
      return s_error;
    }
    p++;
    goto s_n_llpkgc_file__internal__n_pkgc_file_barewords_escaped_comment;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_1;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_2: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_3;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_3: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_4;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_1: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_4: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_7: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_2: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_2;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_2;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_9: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_2;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_2: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_2;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__value_resume: {
    switch (llpkgc_file__internal__c_load_llpkgc_file__value_resume(state, p, endp)) {
      case 0:
        goto s_n_llpkgc_file__internal__n_pkgc_file_expect_value;
      case 1:
        goto s_n_llpkgc_file__internal__n_pkgc_file_value;
      default:
        goto s_n_llpkgc_file__internal__n_error;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__line_resume: {
    switch (llpkgc_file__internal__c_load_llpkgc_file__line_resume(state, p, endp)) {
      case 0:
        goto s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator;
      case 1:
        goto s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__value_resume;
      default:
        goto s_n_llpkgc_file__internal__n_error;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__line_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_continue_line;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__value_resume: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__value_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_10: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_3;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_load_llpkgc_file__text_resume: {
    switch (llpkgc_file__internal__c_load_llpkgc_file__text_resume(state, p, endp)) {
      case 0:
        goto s_n_llpkgc_file__internal__n_pkgc_file_value_literal;
      default:
        goto s_n_llpkgc_file__internal__n_error;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__text_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_double_backslash;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_8: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_3: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_3;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_3;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_11: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_5;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_3: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_2;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_8: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_8(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_value;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_6: {
    state->error = 0xc;
    state->reason = "Value substitution complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__sub_span: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__sub_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) (p + 1);
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__sub_complete;
      return s_error;
    }
    p++;
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__sub_complete;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_9: {
    state->error = 0xd;
    state->reason = "Invalid variable substitution character";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_7: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_7(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__sub_span;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_5: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_1: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_1;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_1;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_10: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_4: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_4;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_4;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_11: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_5: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_5;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_5;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_4: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_1;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume_1: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__text_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_backslash_literal;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume_1: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__line_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_continue_line;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__value_resume_1: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__value_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume_1;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_12: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_6: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_6;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_6;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_13: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_7: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_7;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_7;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume_2: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__text_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_double_backslash;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_14: {
    state->error = 0xb;
    state->reason = "Value literal complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__lit_span_8: {
    const unsigned char* start;
    int err;

    start = state->_span_pos1;
    state->_span_pos1 = NULL;
    err = llpkgc_file__lit_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_8;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lit_complete_8;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_5: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_3;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_6: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_12: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_6;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_6: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume_2: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__line_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_continue_line;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__value_resume_2: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__value_resume_2(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume_2;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__text_resume_3: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__text_resume(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_double_backslash;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_13: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_6(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__lit_span_8;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_7: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_4;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_5: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_5(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_expect_value;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_3: {
    state->error = 0x7;
    state->reason = "Property complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__prop_decl_complete: {
    switch (llpkgc_file__prop_decl_complete(state, p, endp)) {
      case 0:
        goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_5;
      default:
        goto s_n_llpkgc_file__internal__n_error_3;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_error_15: {
    state->error = 0x8;
    state->reason = "Variable complete error";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_error;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_llpkgc_file__var_decl_complete: {
    switch (llpkgc_file__var_decl_complete(state, p, endp)) {
      case 0:
        goto s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_5;
      default:
        goto s_n_llpkgc_file__internal__n_error_15;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__line_resume_3: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__line_resume_3(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_pkgc_file_continue_line;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_14: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_6;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_15: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_7;
    }
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_8: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_5;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_3: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__ident_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) p;
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator;
      return s_error;
    }
    goto s_n_llpkgc_file__internal__n_pkgc_file_maybe_separator;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_4: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__ident_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) (p + 1);
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_pkgc_file_ident_continue_line;
      return s_error;
    }
    p++;
    goto s_n_llpkgc_file__internal__n_pkgc_file_ident_continue_line;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_span_end_llpkgc_file__ident_span_5: {
    const unsigned char* start;
    int err;

    start = state->_span_pos0;
    state->_span_pos0 = NULL;
    err = llpkgc_file__ident_span(state, start, p);
    if (err != 0) {
      state->error = err;
      state->error_pos = (const char*) (p + 1);
      state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_pkgc_file_ident_escaped_comment;
      return s_error;
    }
    p++;
    goto s_n_llpkgc_file__internal__n_pkgc_file_ident_escaped_comment;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_pause_9: {
    state->error = 0x4;
    state->reason = "Lookahead required";
    state->error_pos = (const char*) p;
    state->_current = (void*) (intptr_t) s_n_llpkgc_file__internal__n_invoke_llpkgc_file__lookahead_backslash_6;
    return s_error;
    UNREACHABLE;
  }
  s_n_llpkgc_file__internal__n_invoke_update_llpkgc_file__unfinished_4: {
    switch (llpkgc_file__internal__c_update_llpkgc_file__unfinished_4(state, p, endp)) {
      default:
        goto s_n_llpkgc_file__internal__n_span_start_llpkgc_file__ident_span_5;
    }
    UNREACHABLE;
  }
}

int llpkgc_file__internal_execute(llpkgc_file__internal_t* state, const char* p, const char* endp) {
  llparse_state_t next;

  /* check lingering errors */
  if (state->error != 0) {
    return state->error;
  }

  /* restart spans */
  if (state->_span_pos0 != NULL) {
    state->_span_pos0 = (void*) p;
  }
  if (state->_span_pos1 != NULL) {
    state->_span_pos1 = (void*) p;
  }

  next = llpkgc_file__internal__run(state, (const unsigned char*) p, (const unsigned char*) endp);
  if (next == s_error) {
    return state->error;
  }
  state->_current = (void*) (intptr_t) next;

  /* execute spans */
  if (state->_span_pos0 != NULL) {
    int error;

    error = ((llpkgc_file__internal__span_cb) state->_span_cb0)(state, state->_span_pos0, (const char*) endp);
    if (error != 0) {
      state->error = error;
      state->error_pos = endp;
      return error;
    }
  }
  if (state->_span_pos1 != NULL) {
    int error;

    error = llpkgc_file__lit_span(state, state->_span_pos1, (const char*) endp);
    if (error != 0) {
      state->error = error;
      state->error_pos = endp;
      return error;
    }
  }

  return 0;
}
