/* Distributed under the OSI-approved BSD 3-Clause License.
   See accompanying file LICENSE.rst for details.  */
/* This code was generated by llpkgc, do not edit it by hand
   See: https://gitlab.kitware.com/utils/llpkgc  */


#ifndef INCLUDE_LLPKGC_FRAG__INTERNAL_H_
#define INCLUDE_LLPKGC_FRAG__INTERNAL_H_
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef struct llpkgc_frag__internal_s llpkgc_frag__internal_t;
struct llpkgc_frag__internal_s {
  int32_t _index;
  void* _span_pos0;
  int32_t error;
  const char* reason;
  const char* error_pos;
  void* data;
  void* _current;
  void* llpkgc_frag__settings;
  uint8_t llpkgc_frag__state;
  uint8_t llpkgc_frag__eof;
  uint8_t llpkgc_frag__lookahead;
};

int llpkgc_frag__internal_init(llpkgc_frag__internal_t* s);
int llpkgc_frag__internal_execute(llpkgc_frag__internal_t* s, const char* p, const char* endp);

#ifdef __cplusplus
}  /* extern "C" */
#endif
#endif  /* INCLUDE_LLPKGC_FRAG__INTERNAL_H_ */
