include(RunCMake)

run_cmake(MATH)
run_cmake(MATH-WrongArgument)
run_cmake(MATH-DoubleOption)
run_cmake(MATH-TooManyArguments)
run_cmake(MATH-InvalidExpression)
run_cmake(MATH-ToleratedExpression)
run_cmake(MATH-DivideByZero)
run_cmake(MATH-ModByZero)
run_cmake(MATH-DivideMinByMinusOne)
run_cmake(MATH-ModMinByMinusOne)
run_cmake(MATH-INCREMENT-NotEnoughArgs)
run_cmake(MATH-INCREMENT-TooManyArgs)
run_cmake(MATH-INCREMENT-Undefined)
run_cmake(MATH-INCREMENT-Empty)
run_cmake(MATH-INCREMENT-Invalid)
run_cmake(MATH-INCREMENT-Extra)
run_cmake(MATH-DECREMENT-NotEnoughArgs)
run_cmake(MATH-DECREMENT-TooManyArgs)
run_cmake(MATH-DECREMENT-Undefined)
run_cmake(MATH-DECREMENT-Empty)
run_cmake(MATH-DECREMENT-Invalid)
run_cmake(MATH-DECREMENT-Extra)

if(CMake_TEST_MATH_OVERFLOW)
  run_cmake_script(Overflow)
endif()
